--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------
This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
      Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
http://wiki.darkrp.com/index.php/DarkRP:CustomJobFields

Add your custom jobs under the following line:
---------------------------------------------------------------------------]]



TEAM_UNTRAINED = DarkRP.createJob("Cadet", {
    color = Color(102, 102, 102, 255),
    model = {"models/doublehexgaming/dhgclonerecruit/dhgclonerecruit.mdl"},
    description = [[Untrained Clone]],
    weapons = {"salute","Keys"},
    command = "cadet",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Untrained",
    PlayerLoadout = function(ply) ply:SetHealth(100) end,
})



TEAM_CT = DarkRP.createJob("Clone Trooper", {
    color = Color(200, 200, 200, 255),
    model = {"models/doublehexgaming/dhgcloneunassigned/dhgcloneunassigned.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "CT",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_CT = DarkRP.createJob("Clone Medic", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/testm/cmedic.mdl"},
    description = [[Standard Clone Medic]],
    weapons = {"revival_tool", "salute", "med_kit", "weapon_bactainjector", "bf2017_dc15a", "bf2017_dc15s", "bf2017_dc17", "clone_card_c2"},
    command = "CTMEDIC",
    max = 0,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_CT = DarkRP.createJob("Clone ARF", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/91ls/91lst.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17", "realistic_hook",  "bf2017_dc15s","clone_card_c1","bf2017_dc15le"},
    command = "CTARF",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_CT = DarkRP.createJob("Clone Sergeant", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/gggt/gggt.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17", "bf2017_dc15a" , "bf2017_dc15s", "clone_card_c1"},
    command = "CTSGT",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_CT = DarkRP.createJob("Clone Lieutenant", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/ggbt/ggbt.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17",  "bf2017_dc15s" , "bf2017_dc15a", "clone_card_c3"},
    command = "CTLT",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_CT = DarkRP.createJob("Clone Captain", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/ggrt/ggrt.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17",  "bf2017_dc15a" , "cross_arms_swep", "bf2017_dc15s", "clone_card_c3"},
    command = "CTCPT",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_CT = DarkRP.createJob("Clone Commander", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/gguc/gguc.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17" ,  "bf2017_dc15a" , "cross_arms_swep", "bf2017_dc15s" ,  "clone_card_c4"},
    command = "CTCMD",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_CT = DarkRP.createJob("Head of ARF", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/ggbcgarf/ggbcgarf.mdl"},
    description = [[Standard Clone Trooper]],
    weapons = {"salute","bf2017_dc17","bf2017_dc15s", "cross_arms_swep", "realistic_hook",  "clone_card_c3", "bf2017_dc15le"},
    command = "CTHOA",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Clone Trooper",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(115) end,
})
TEAM_TRAUMA = DarkRP.createJob("Trauma Trooper", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/clone/traumatrooper.mdl"},
    description = [[Member of Savage Squad, lead by Captain Trauma.]],
    weapons = {"salute", "bf2017_valken" , "bf2017_dc15s" ,"realistic_hook", "bf2017_dc17", "clone_card_c1", "bf2017_dc15le"},
    command = "traumatroop",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Trauma",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(100) end,
})
TEAM_TRAUMA = DarkRP.createJob("Captain Trauma", {
    color = Color(200, 200, 200, 255),
    model = {"models/player/clone/trauma.mdl"},
    description = [[Leader of the group of ARF troopers known as Savage Squad.]],
    weapons = {"salute", "bf2017_valken", "bf2017_dc15s", "realistic_hook", "cross_arms_swep", "bf2017_dc17", "clone_card_c3", "bf2017_dc15le"},
    command = "captrauma",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Trauma",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(115) end,
})

TEAM_104TH = DarkRP.createJob("104th Trooper", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/wolftrooper.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "104thTrooper",
    max = 15,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_104TH = DarkRP.createJob("104th Medic", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/wolfmedic.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"revival_tool", "salute", "med_kit", "weapon_bactainjector", "bf2017_dc15s", "bf2017_dc17", "bf2017_dc15a", "clone_card_c1"},
    command = "104thMedic",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_104TH = DarkRP.createJob("104th Engineer", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/wolfnco.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17",  "clone_card_c2", "repair_tool", "bf2017_dc15a"},
    command = "104thEngineer",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_104TH = DarkRP.createJob("104th Heavy", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/wolfheavy.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute","bf2017_dc17", "chaingun_servius",   "bf2017_dc15a",   "bf2017_dc15s",   "clone_card_c1"},
    command = "104thHeavy",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_104TH = DarkRP.createJob("104th Officer", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/wolfofficer.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c3"},
    command = "104thOfficer",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_104TH = DarkRP.createJob("104th Comet", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/comet.mdl"},
    description = [[104th Comet]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c3"},
    command = "104thcomet",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_104TH = DarkRP.createJob("104th Boost", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/betatrooper/betatrooper.mdl"},
    description = [[104th Boost]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c2"},
    command = "104thboost",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_104TH = DarkRP.createJob("104th Wolfpack", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/jettrooper1.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "104thWolfpack",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(125) end,
})
TEAM_104TH = DarkRP.createJob("Warthog", {
    color = Color(128, 128, 128, 255),
    model = "models/player/jon/jon.mdl",
    description = [[Warthog]],
    weapons = {"bf2017_dc15s", "keys", "pocket",  "salute", "bf2017_dc17","bf2017_dc15a", "clone_card_c1"},
    command = "wart",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_104TH = DarkRP.createJob("104th Juggernaut", {
    color = Color(128, 128, 128, 255),
    model = "models/gonzo/juggernautremaster/juggernautremaster.mdl",
    description = [[Juggernaut]],
    weapons = {"keys", "pocket", "bf2017_dc17", "salute", "bf2017_dc15le",  "clone_card_c2", "b2_wrist_blaster"},
    command = "jug",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_104TH = DarkRP.createJob("104th Wolffe", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/clone/commanderwolffe.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c4"},
    command = "104thWolffe",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("104th ARC", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/cgiarc104th/cgiarc104th.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_valken", "realistic_hook", "clone_card_c1", "bf2017_dc15le"},
    command = "104thARC",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_104TH = DarkRP.createJob("104th ARF", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/104a/104a.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "realistic_hook", "clone_card_c1", "bf2017_valken"},
    command = "104thARF",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_104TH = DarkRP.createJob("104th Pilot", {
    color = Color(128, 128, 128, 255),
    model = {"models/player/gg104p/gg104p.mdl"},
    description = [[Standard Trooper in the 104th]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "clone_card_c1", "bf2017_dc15a"},
    command = "104thPilot",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "104th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})

TEAM_212TH = DarkRP.createJob("212th Trooper", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/212th/c212th trooper.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "212trp",
    max = 15,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("212th Medic", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/212th medic/212th medic.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"revival_tool", "salute", "med_kit", "weapon_bactainjector", "bf2017_dc15s", "bf2017_dc17", "bf2017_dc15a"},
    command = "212med",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("2nd Airborne", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/2nda/cgi2nda.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "2air",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(125) end,
})
TEAM_212TH = DarkRP.createJob("212th ARF", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/lastbastion/212arf/212arf.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "bf2017_valken", "realistic_hook", "clone_card_c1"},
    command = "212arf",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("212th Engineer", {
    color = Color(253, 106, 2, 255),
    model = {"models/lazarusgaming/lg212thsergeant/lg212thsergeant.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17", "clone_card_c2", "repair_tool"},
    command = "212eng",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("212th Ghost Company", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/time/garc/garc.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "212ghst",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(150) end,
})
TEAM_212TH = DarkRP.createJob("212th Officer", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/212thlt/c212thlt.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c3"},
    command = "212off",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_212TH = DarkRP.createJob("212th Waxer", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/waxer/waxer.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "waxer",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_212TH = DarkRP.createJob("212th Boil", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/boil/boil.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute","bf2017_dc17",   "bf2017_dc15a",   "bf2017_dc15s",   "clone_card_c1","tfa_dc15a_expanded"},
    command = "boil",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("212th Cody", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/phenomenalnations/cody.mdl"},
    description = [[Standard 212th Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c4"},
    command = "cody",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_212th = DarkRP.createJob("Foxtrot Jolwe", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/trinitygaming/rcfoxtrottech.mdl"},
    description = [[The medic of Foxtrot Group]],
    weapons = {"weapon_bactanade", "weapon_medkit", "weapon_bactainjector", "revival_tool", "bf2017_dc15s", "weapon_752_dc17m_br", "bf2017_dc17", "cross_arms_swep"},
    command = "foxtrotmed",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
    PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(100) end,
})

TEAM_212th = DarkRP.createJob("Foxtrot Akaan", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/sono/starwars/nuck.mdl"},
    description = [[The heavy of Foxtrot Group]],
    weapons = {"chaingun_servius", "tfa_swch_clonelauncher_3", "tfa_dc17m_shotgun", "bf2017_dc17", "cross_arms_swep", "weapon_752_dc17m_br"},
    command = "foxtrothvy",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
    PlayerSpawn = function(ply) ply:SetHealth(250) ply:SetArmor(200) end,
})

TEAM_212th = DarkRP.createJob("Foxtrot McJoe", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/trinitygaming/rcfoxtrotmarksman.mdl"},
    description = [[The engineer and slicer of Foxtrot Group]],
    weapons = {"cross_arms_swep", "repair_tool", "bf2017_dc15s", "weapon_752_dc17m_br", "bf2017_dc17"},
    command = "foxtroteng",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
    PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(100) end,
})

TEAM_212th = DarkRP.createJob("Foxtrot Big Box", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/trinitygaming/rcfoxtroteod.mdl"},
    description = [[The marksman of Foxtrot Group]],
    weapons = {"cross_arms_swep", "weapon_752_dc17m_br", "weapon_752_dc17m_sn", "bf2017_dc15le", "bf2017_valken", "dc17grapple"},
    command = "foxtrotsnip",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
    PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(100) end,
 })   
TEAM_212TH = DarkRP.createJob("212th Gregor", {
    color = Color(253, 106, 2, 255),
    model = {"models/reizer_cgi_p2/rc_gregor_dirty/rc_gregor_dirty.mdl"},
    description = [[The leader of Foxtrot Group]],
    weapons = {"salute","bf2017_dc15le", "weapon_752_dc17m_br", "bf2017_dc17", "tfa_dc17m_shotgun", "clone_card_c3"},
    command = "gregor",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_212TH = DarkRP.createJob("212th Barlex", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/2ndalt/2ndalt.mdl"},
    description = [[212th barlex]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17", "bf2017_dc15a", "clone_card_c2"},
    command = "barlex",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(100) end,
})
TEAM_212TH = DarkRP.createJob("212th Pilot", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/gg212p/gg212p.mdl"},
    description = [[212th zoom zoom]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17", "clone_card_c1", "bf2017_dc15a"},
    command = "212pilot",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(50) end,
})
TEAM_ARC = DarkRP.createJob("212th ARC Trooper", {
    color = Color(253, 106, 2, 255),
    model = {"models/player/cgiarc212th/cgiarc212th.mdl"},
    description = [[212th ARC Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15le", "realistic_hook", "bf2017_dc15s", "bf2017_valken", "clone_card_c1"},
    command = "ARC212",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "212th",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})

TEAM_501ST = DarkRP.createJob("501st Trooper", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/501t/501.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "501trp",
    max = 15,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Medic", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/501medic/501medic.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"revival_tool", "salute", "med_kit", "weapon_bactainjector", "bf2017_dc15s", "bf2017_dc17", "bf2017_dc15a", "clone_card_c2"},
    command = "501med",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Heavy", {
    color = Color(34, 119, 255, 255),   
	model = {"models/player/501heavy/501heavy.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "chaingun_servius", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "501hvy",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_501ST = DarkRP.createJob("501st Engineer", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/clone/pgriot.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc15a", "bf2017_dc15s", "bf2017_dc17", "clone_card_c2", "repair_tool"},
    command = "501eng",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Rex", {
    color = Color(34, 119, 255, 255),   
	model = {"models/player/phenomenalnations/rex.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c4"},
    command = "rex",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Jesse", {
    color = Color(34, 119, 255, 255), 
	model = {"models/player/jesse/jesse.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c2"},
    command = "jesse",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_501ST = DarkRP.createJob("501st Fives", {
    color = Color(34, 119, 255, 255),    
	model = {"models/player/cgiarcfives/cgiarcfives.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c2"},
    command = "fives",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Echo", {
    color = Color(34, 119, 255, 255),   
	model = {"models/player/cgiarcecho/cgiarcecho.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c2"},
    command = "echo",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Kix", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/kix/kix.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"revival_tool", "salute", "med_kit", "weapon_bactainjector", "bf2017_dc15s", "bf2017_dc17", "bf2017_dc15a", "clone_card_c1"},
    command = "kix",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(115) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Hardcase", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/omo/hardcase/hardcase.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "chaingun_servius", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "hardcase",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_501ST = DarkRP.createJob("501st ARF", {
    color = Color(34, 119, 255, 255), 
	model = {"models/player/lastbastion/501arf/501arf.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "clone_card_c1", "realistic_hook","bf2017_valken"},
    command = "501arf",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Anvil", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/clone/pgcom.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c3"},
    command = "anvil",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Officer", {
    color = Color(34, 119, 255, 255),  
	model = {"models/player/clone/501stofficer.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c3"},
    command = "501off",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_501ST = DarkRP.createJob("501st Commander", {
    color = Color(34, 119, 255, 255), 
	model = {"models/player/clone/501stmaj.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "cross_arms_swep", "bf2017_dc15s", "clone_card_c4"},
    command = "501cmd",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Appo", {
    color = Color(34, 119, 255, 255),
	model = {"models/player/clone/501stnco.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "appo",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(150) end,
})
TEAM_501ST = DarkRP.createJob("501st Hawk", {
    color = Color(34, 119, 255, 255),   
	model = {"models/hawk/hawk.mdl"},
    description = [[Standard 501st Trooper]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1"},
    command = "hawk",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_501ST = DarkRP.createJob("501st Pilot", {
    color = Color(34, 119, 255, 255),
	model = {"models/player/gg501p/gg501p.mdl"},
    description = [[501st Man]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "bf2017_dc15a", "clone_card_c1"},
    command = "501pilot",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(50) end,
})
TEAM_501ST = DarkRP.createJob("501st ARC Trooper", {
    color = Color(34, 119, 255, 255),    
	model = {"models/player/cgiarc5th/cgiarc5th.mdl"},
    description = [[501st ARC Trooper]],
    weapons = {"salute", "bf2017_dc17", "realistic_hook", "bf2017_dc15le", "bf2017_dc15s", "clone_card_c1", "bf2017_valken"},
    command = "ARC501",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "501st",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})

TEAM_CG = DarkRP.createJob("CG Trooper", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/ggshockt/ggshockt.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"salute","arrest_stick","stunstick","unarrest_stick","bf2017_dc17","bf2017_dc15a","bf2017_dc15s","clone_card_c3","weapon_cuff_elastic","door_ram","weaponchecker"},
    command = "CGtrp",
    max = 15,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(125) end,
})
TEAM_CG = DarkRP.createJob("CG Riot", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/612th/cgi612th.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"salute","arrest_stick","stunstick","unarrest_stick","bf2017_dc17","chaingun_servius","bf2017_dc15a","bf2017_dc15s","clone_card_c3","weapon_policeshield","weapon_cuff_elastic","door_ram","weaponchecker"},
    command = "CGriot",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_CG = DarkRP.createJob("CG Officer", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/gingers_cg_lieut/gingers_cg_lieut.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"salute","arrest_stick","stunstick","unarrest_stick","bf2017_dc17","cross_arms_swep","bf2017_dc15a","bf2017_dc15s","clone_card_c4","weapon_cuff_elastic","door_ram","weaponchecker"},
    command = "CGoff",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(125) end,
})
TEAM_CG = DarkRP.createJob("CG Thorn", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/ggthorn/ggthorn.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"salute","arrest_stick","stunstick","cross_arms_swep","unarrest_stick","bf2017_dc17","bf2017_dc15a","bf2017_dc15s","clone_card_c4","weapon_cuff_elastic","weapon_policeshield","door_ram","weaponchecker"},
    command = "CGthorn",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})
TEAM_CG = DarkRP.createJob("CG Hound Trooper", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/gghound/gghound.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"salute","arrest_stick","stunstick","realistic_hook","unarrest_stick","bf2017_dc17","bf2017_dc15s","bf2017_dc15a","clone_card_c3","weapon_cuff_elastic","door_ram","weaponchecker"},
    command = "CGht",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(115) end,
})
TEAM_CG = DarkRP.createJob("CG Medic", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/ggshockmed/ggshockmed.mdl"},
    description = [[Standard CG Trooper]],
    weapons = {"revival_tool","salute","arrest_stick","stunstick","unarrest_stick","med_kit","weapon_bactainjector","bf2017_dc15s","bf2017_dc17","bf2017_dc15a","clone_card_c3","weapon_cuff_elastic","door_ram","weaponchecker",},
    command = "CGmed",
    max = 3,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(115) end,
})
TEAM_CG = DarkRP.createJob("CG Pilot", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/ggcguardp/ggcguardp.mdl"},
    description = [[CG zoom zoom]],
    weapons = {"salute","bf2017_dc17","bf2017_dc15s","clone_card_c3","weapon_cuff_elastic","door_ram","arrest_stick","stunstick","unarrest_stick","weaponchecker","bf2017_dc15a"},
    command = "cgpilot",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("CG ARC Trooper", {
    color = Color(194, 24, 7, 255),
    model = {"models/player/cgiarcshock/cgiarcshock.mdl"},
    description = [[CG ARC Trooper]],
    weapons = {"salute","bf2017_dc17","bf2017_dc15a","bf2017_dc15s","clone_card_c3","arrest_stick","stunstick","unarrest_stick","weapon_cuff_elastic","realistic_hook","door_ram","weaponchecker"},
    command = "ARCCG",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "CG",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_CG = DarkRP.createJob("CG Fox", {
    color = Color(194, 24, 7, 255),
    model = "models/player/fox/ccfox.mdl",
    description = [[Fox]],
    weapons = {"door_ram", "arrest_stick", "pocket", "keys", "unarrest_stick", "bf2017_dc17", "bf2017_dc15s", "bf2017_dc15a", "clone_card_c3", "cross_arms_swep", "salute", "weaponchecker","stunstick"},
    command = "fox",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
PlayerSpawn = function(ply) ply:SetHealth(200) ply:SetArmor(150) end,
})

TEAM_NAVY = DarkRP.createJob("Navy Medic", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/bridgestaff/cgibridgestaff.mdl",
			"models/player/medicalfleet/medicalfleet.mdl"},
    description = [[Navy Man]],
    weapons = {"revival_tool","salute","med_kit", "cross_arms_swep", "weapon_bactainjector", "bf2017_dc17", "clone_card_c3navy", "bf2017_dc15s"},
    command = "navymed",
    max = 7,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(100) end,
})
TEAM_NAVY = DarkRP.createJob("Navy Engineer", {
    color = Color(11, 80, 115, 255),
    model = {"models/lazarusgaming/lgcloneengineer/lgcloneengineer.mdl"},
    description = [[Navy Man]],
    weapons = {"salute","bf2017_dc17", "cross_arms_swep", "clone_card_c3navy", "repair_tool","bf2017_dc15s"},
    command = "navyeng",
    max = 8,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(100) end,
})
TEAM_NAVY = DarkRP.createJob("Navy", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/fleet/fleet.mdl"},
    description = [[Navy Man]],
    weapons = {"salute","bf2017_dc17", "cross_arms_swep", "clone_card_c3navy","bf2017_dc15s"},
    command = "navyman",
    max = 10,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(100) end,
})
TEAM_NAVY = DarkRP.createJob("Navy Officer", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/blackfleet/blackfleet.mdl"},
    description = [[Navy Man]],
    weapons = {"salute", "bf2017_dc17", "cross_arms_swep", "clone_card_c3navy","bf2017_dc15s"},
    command = "navyoff",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(100) end,
})
TEAM_NAVY = DarkRP.createJob("Admiral", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/ggrnc/ggrnc.mdl"},
    description = [[Navy Man]],
    weapons = {"salute","bf2017_dc17", "cross_arms_swep", "clone_card_c3navy", "bf2017_dc15s"},
    command = "admiral",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(200) end,
})
TEAM_NAVY = DarkRP.createJob("Pilot", {
    color = Color(11, 80, 115, 255),
    model = {"models/broadside/broadside.mdl"},
    description = [[Navy Man]],
    weapons = {"salute", "bf2017_dc17", "bf2017_dc15s", "clone_card_c3navy","bf2017_dc15a"},
    command = "navypilot",
    max = 5,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetArmor(100) end,
})
TEAM_NAVY = DarkRP.createJob("Pilot Squadron Leader", {
    color = Color(11, 80, 115, 255),
    model = {"models/atte/atte.mdl"},
    description = [[Navy Man]],
    weapons = {"salute", "bf2017_dc17", "cross_arms_swep", "bf2017_dc15s", "clone_card_c3navy", "bf2017_dc15a"},
    command = "squadleader",
    max = 1,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(150) ply:SetArmor(100) end,
})
TEAM_NAVY = DarkRP.createJob("Naval Trooper", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/ggsierra/ggsierra.mdl"},
    description = [[Members of the Navy, armed and ready for combat]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17", "clone_card_c3navy"},
    command = "NavalTrooper",
    max = 15,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})
TEAM_NAVY = DarkRP.createJob("Naval Trooper Medic", {
    color = Color(11, 80, 115, 255),
    model = {"models/player/ggsierra/ggsierra.mdl"},
    description = [[Members of the Navy, equiped with armor, weapons and medical equipment]],
    weapons = {"salute", "bf2017_dc15s", "bf2017_dc17", "clone_card_c3navy", "revival_tool", "salute", "med_kit", "weapon_bactainjector"},
    command = "NavalTrooperMedic",
    max = 10,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Navy",
	PlayerSpawn = function(ply) ply:SetHealth(125) ply:SetArmor(100) end,
})

TEAM_ARC = DarkRP.createJob("ARC Leader", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/cgiarccommander/cgiarccommander.mdl"},
    description = [[Definitely not Colt]],
    weapons = {"salute", "bf2017_dc17", "bf2017_valken", "cross_arms_swep", "bf2017_dc15le", "bf2017_dc15s", "clone_card_c3","realistic_hook"},
    command = "ARCcolt",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("ARC Heavy", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/cgiarcnco/cgiarcnco.mdl"},
    description = [[ARC Trooper]],
    weapons = {"salute","bf2017_dc17", "chaingun_servius", "bf2017_dc15le", "bf2017_dc15s", "clone_card_c1", "realistic_hook"},
    command = "ARChvy",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("ARC Medic", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/cgiarc187th/cgiarc187th.mdl"},
    description = [[ARC Trooper]],
    weapons = {"revival_tool","salute","med_kit", "weapon_bactainjector", "bf2017_dc15s", "bf2017_dc17", "clone_card_c2", "bf2017_dc15le", "bf2017_valken","realistic_hook"},
    command = "ARCmed",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("ARC Trooper", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/cgiarclt/cgiarclt.mdl"},
    description = [[ARC Trooper]],
    weapons = {"salute","bf2017_dc17", "bf2017_valken", "bf2017_dc15a", "bf2017_dc15s", "clone_card_c1","realistic_hook"},
    command = "ARCtrp",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("ARC Pilot", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/cgiarc612th/cgiarc612th.mdl"},
    description = [[ARC Man]],
    weapons = {"salute","bf2017_dc17", "bf2017_dc15le", "bf2017_valken", "bf2017_dc15s", "clone_card_c1", "realistic_hook"},
    command = "arcpilot",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
})
TEAM_ARC = DarkRP.createJob("ARC Captain", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/clone/arccpt.mdl"},
    description = [[Definitely not Colt]],
    weapons = {"salute","bf2017_dc17","bf2017_valken","bf2017_dc15a","bf2017_dc15s","clone_card_c3","realistic_hook"},
    command = "ARCCPT",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
	
})
TEAM_ARC = DarkRP.createJob("ARC LT", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/clone/arclt.mdl"},
    description = [[Definitely not Colt]],
    weapons = {"salute","bf2017_dc17","bf2017_valken","bf2017_dc15le","bf2017_dc15s","clone_card_c2","realistic_hook"},
    command = "ARCLT",
    max = 4,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
	
})
TEAM_ARC = DarkRP.createJob("ARC SGT", {
    color = Color(0, 200, 0, 255),
    model = {"models/player/clone/arcnco.mdl"},
    description = [[Definitely not Colt]],
    weapons = {"salute","bf2017_dc17","bf2017_valken","bf2017_dc15le","bf2017_dc15s","clone_card_c1","realistic_hook"},
    command = "ARCSGT",
    max = 6,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "ARC",
	PlayerSpawn = function(ply) ply:SetHealth(175) ply:SetArmor(150) end,
	
})

TEAM_JEDI = DarkRP.createJob("General Skywalker", {
    color = Color(170, 11, 219, 255),
    model = "models/tfa/comm/gg/pm_sw_anakin_v2.mdl",
    description = [[Jedi General Skywalker]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "Ani",
    max = 1,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})

TEAM_JEDI = DarkRP.createJob("General Kenobi", {
    color = Color(170, 11, 219, 255),
    model = "models/tfa/comm/gg/pm_sw_obiwan_alt.mdl",
    description = [[Jedi General Kenobi]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "obi",
    max = 1,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})
TEAM_JEDI = DarkRP.createJob("General Windu", {
    color = Color(170, 11, 219, 255),
    model = "models/player/mace/mace.mdl",
    description = [[Jedi General Windu]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "mace",
    max = 1,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})
TEAM_JEDI = DarkRP.createJob("General Plo Koon", {
    color = Color(170, 11, 219, 255),
    model = "models/player/plokoon/plokoon.mdl",
    description = [[Jedi General Koon]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "plo",
    max = 1,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
		PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})
TEAM_JEDI = DarkRP.createJob("Jedi Master", {
    color = Color(170, 11, 219, 255),
    model = "models/grealms/characters/jedibattlelord/jedibattlelord_07.mdl",
    description = [[Jedi Master]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "jedi",
    max = 3,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
		PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})

TEAM_JEDI = DarkRP.createJob("Jedi Master Quinlan Vos", {
    color = Color(170, 11, 219, 255),
    model = "models/tfa/comm/gg/pm_sw_quinlanvos.mdl",
    description = [[Jedi Master Quinlan Vos]],
    weapons = {"weapon_lightsaber_allpowers","weapon_forceheal"},
    command = "vos",
    max = 1,
    salary = 400,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
		PlayerSpawn = function(ply) ply:SetHealth(3500) ply:SetArmor(255) end,
})



--[[---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------]]
GAMEMODE.DefaultTeam = TEAM_UNTRAINED


--[[---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------]]
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = false,
	[TEAM_CHIEF] = false,
	[TEAM_MAYOR] = false,
}

--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
DarkRP.addHitmanTeam(TEAM_MOB)